name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions!
on: [push]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job is automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checks out repository code
        uses: actions/checkout@v5
      - run: echo "The ${{ github.repository }} has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on your runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
